# Usar una imagen oficial de Node.js como base
FROM node:22

# Crear y establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del proyecto (sin node_modules)
COPY . .

# Exponer el puerto en el que tu aplicación correrá
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
