services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    ports:
      - $PG_LOCAL_PORT:$PG_DOCKER_PORT
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - $LOCAL_PORT:$DOCKER_PORT


volumes:
  postgres_data: